//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_Booking_App
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Model1Container1 : DbContext
    {
        public Model1Container1()
            : base("name=Model1Container1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customer> CustomerSet { get; set; }
        public virtual DbSet<CreditCard> CreditCardSet { get; set; }
        public virtual DbSet<Hotel> HotelSet { get; set; }
        public virtual DbSet<Booking> BookingSet { get; set; }
        public virtual DbSet<HotelOwner> HotelOwnerSet { get; set; }
        public virtual DbSet<Currency> CurrencySet { get; set; }
        public virtual DbSet<Evaluation> EvaluationSet { get; set; }
        public virtual DbSet<Service> ServiceSet { get; set; }
        public virtual DbSet<Room> RoomSet { get; set; }
    }
}
